#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

IrPin = 18
count = 0
last_time = 0.0
COOLDOWN = 0.6  # seconds

def setup():
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(IrPin, GPIO.IN, pull_up_down=GPIO.PUD_UP)

def cnt(channel=None):
    global count, last_time
    now = time.time()
    # If enough time passed since last count, increment
    if now - last_time >= COOLDOWN:
        count += 1
        last_time = now
        print('Beam disruption. cnt =', count)

def loop():
    GPIO.add_event_detect(IrPin, GPIO.FALLING, callback=cnt, bouncetime=50)
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        pass

def destroy():
    GPIO.cleanup()

if __name__ == '__main__':
    setup()
    try:
        loop()
    except KeyboardInterrupt:
        destroy()
